[package]
name = "image_process"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/handler.rs"

[dependencies]
axum = { version = "0.8.8", features = ["multipart"] }
rust-s3 = "0.37.1"
chrono = "0.4.43"
log = "0.4.29"
env_logger = "0.11.9"
